/* One-command training: `tgc train SOURCE`.
 *
 *   1. load SOURCE (any format data.c knows), infer column kinds, pick the
 *      target (or --target)
 *   2. seeded train/validation split; fit the featurization on training rows
 *   3. generate an editable Technograd training model that uses
 *      `train <loss> with <optimizer>`, and a frozen inference model
 *   4. train online for several epochs, evaluate each epoch on a forward-only
 *      copy (updates and backward pass removed), keep the best weights by
 *      validation loss, stop early
 *   5. write OUTDIR/{model.tg, infer.tg, infer.c, weights.*.bin,
 *      features.tgf, report.txt}
 *
 * `tgc predict OUTDIR SOURCE` featurizes new raw data with the saved spec and
 * runs the inference model; `tgc data inspect SOURCE` shows what was inferred;
 * `tgc data prep SOURCE -o out.csv` writes the numeric features. */
#include "tg.h"
#include "data.h"

#include <ctype.h>
#include <math.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>

typedef struct {
	const char *source, *target, *out, *optimizer;
	int epochs, hidden, max_rows, seed, text_dim;
	double lr, val;
} Opts;

static void usage_data(void)
{
	fputs("usage:\n"
	      "  tgc data inspect SOURCE [--target COL]\n"
	      "  tgc data prep SOURCE -o OUT.csv [--target COL]\n"
	      "  tgc train SOURCE [-o DIR] [--target COL] [--epochs N] [--hidden H] [--lr X]\n"
	      "                   [--optimizer sgd|momentum|adam|adamw|muon] [--val FRACTION] [--max-rows N]\n"
	      "                   [--text-dim N] [--seed S]\n"
	      "  tgc predict DIR SOURCE [-o OUT.csv]\n"
	      "SOURCE: a .csv/.tsv/.json/.jsonl/.npy file, or hf:OWNER/NAME[/CONFIG[/SPLIT]]\n",
	      stderr);
	exit(2);
}

static void parse_opts(int argc, char **argv, int first, Opts *o)
{
	for (int i = first; i < argc; i++) {
		const char *a = argv[i];
		const char *v = i + 1 < argc ? argv[i + 1] : NULL;
		if (!v && strncmp(a, "--", 2) == 0) usage_data();
		if (!strcmp(a, "-o")) o->out = v;
		else if (!strcmp(a, "--target")) o->target = v;
		else if (!strcmp(a, "--epochs")) o->epochs = atoi(v);
		else if (!strcmp(a, "--hidden")) o->hidden = atoi(v);
		else if (!strcmp(a, "--lr")) o->lr = atof(v);
		else if (!strcmp(a, "--optimizer")) o->optimizer = v;
		else if (!strcmp(a, "--val")) o->val = atof(v);
		else if (!strcmp(a, "--max-rows")) o->max_rows = atoi(v);
		else if (!strcmp(a, "--seed")) o->seed = atoi(v);
		else if (!strcmp(a, "--text-dim")) o->text_dim = atoi(v);
		else if (!o->source && a[0] != '-') { o->source = a; continue; }
		else die(NULL, 0, "unexpected argument '%s'", a);
		i++;
	}
	if (!o->source) usage_data();
}

static uint32_t rs;
static uint32_t rnd(void)
{
	rs ^= rs << 13;
	rs ^= rs >> 17;
	rs ^= rs << 5;
	return rs;
}

static void shuffle(int *v, int n)
{
	for (int i = n - 1; i > 0; i--) {
		int k = (int)(rnd() % (uint32_t)(i + 1)), t = v[i];
		v[i] = v[k];
		v[k] = t;
	}
}

static void model_name(const char *src, char *out, size_t n)
{
	const char *b = strrchr(src, '/');
	b = b ? b + 1 : src + (strncmp(src, "hf:", 3) ? 0 : 3);
	size_t k = 0;
	for (; *b && *b != '.' && k + 1 < n; b++) out[k++] = isalnum((unsigned char)*b) ? (char)tolower((unsigned char)*b) : '_';
	out[k] = 0;
	if (!k || isdigit((unsigned char)out[0])) snprintf(out, n, "m_%.40s", k ? out : "data");
}

static char *join(const char *dir, const char *file)
{
	char *p = xmalloc(strlen(dir) + strlen(file) + 2);
	sprintf(p, "%s/%s", dir, file);
	return p;
}

static void write_text(const char *path, const char *text)
{
	FILE *f = fopen(path, "w");
	if (!f) die(NULL, 0, "cannot write '%s'", path);
	fputs(text, f);
	if (fclose(f)) die(NULL, 0, "write failed '%s'", path);
}

/* The generated models. Plain Technograd: the user can read and edit them. */
static char *gen_model(const char *name, const Spec *s, int H, const char *opt, double lr, const char *src, int infer)
{
	int D = s->dim, C = s->classify ? s->nclass : 1;
	size_t cap = 8192;
	char *b = xmalloc(cap);
	size_t o = 0;
#define P(...) o += (size_t)snprintf(b + o, cap - o, __VA_ARGS__)
	P("# Generated by `tgc train %s`: %s of '%s' from %d features.\n", src, s->classify ? "classification" : "regression",
	  s->target, D);
	if (infer) P("# Frozen inference model: weights are loaded from the files `tgc train` saved.\n");
	else P("# Training model: weights are state, and every run takes one optimizer step.\n"
	       "# Edit it freely; `tgc batch model.tg data.csv` trains it further.\n");
	P("model %s%s\n\n", name, infer ? "_infer" : "");
	const char *kw = infer ? "param" : "state";
	if (infer) {
		P("%s w1 : f32[%d, %d] = file(\"weights.w1.bin\")\n%s b1 : f32[%d] = file(\"weights.b1.bin\")\n", kw, H, D, kw, H);
		P("%s w2 : f32[%d, %d] = file(\"weights.w2.bin\")\n%s b2 : f32[%d] = file(\"weights.b2.bin\")\n\n", kw, C, H, kw, C);
	} else {
		P("%s w1 : f32[%d, %d] = rand(11, %.6g)\n%s b1 : f32[%d] = zeros\n", kw, H, D, sqrt(6.0 / (D + H)), kw, H);
		P("%s w2 : f32[%d, %d] = rand(12, %.6g)\n%s b2 : f32[%d] = zeros\n\n", kw, C, H, sqrt(6.0 / (H + C)), kw, C);
	}
	P("def net(x: f32[%d]) -> f32[%d]:\n    h = gelu(w1 @ x + b1)\n    return w2 @ h + b2\n\n", D, C);
	if (infer) {
		P("def forward(x: f32[%d]) -> f32[%d]:\n    return %s\n", D, C, s->classify ? "softmax(net(x))" : "net(x)");
	} else if (s->classify) {
		P("def forward(x: f32[%d], target: f32[%d]) -> f32[%d]:\n    logits = net(x)\n"
		  "    train xent(logits, target) with %s(lr=%g)\n    return softmax(logits)\n", D, C, C, opt, lr);
	} else {
		P("def forward(x: f32[%d], target: f32[1]) -> f32[1]:\n    y = net(x)\n"
		  "    train mse(y, target) with %s(lr=%g)\n    return y\n", D, opt, lr);
	}
#undef P
	return b;
}

typedef struct {
	double loss, acc;
} Score;

/* Run rows through a model: the training model takes a step per row, the
 * forward-only evaluation copy just predicts. */
static Score run_rows(Module *m, const Spec *s, const float *X, const float *Y, const int *lab, const int *rows, int n,
		      float *arena, float *out, int *steps)
{
	int D = s->dim, C = s->classify ? s->nclass : 1;
	Score sc = { 0, 0 };
	for (int i = 0; i < n; i++) {
		int r = rows[i];
		const float *in[2] = { X + (size_t)r * (size_t)D, Y + (size_t)r * (size_t)C };
		vm_run_into(m, in, out, steps, arena, NULL);
		if (s->classify) {
			int best = 0;
			for (int c = 1; c < C; c++)
				if (out[c] > out[best]) best = c;
			sc.loss += -log(out[lab[r]] + 1e-12);
			sc.acc += best == lab[r];
		} else {
			double d = out[0] - Y[r];
			sc.loss += d * d;
		}
	}
	sc.loss /= n > 0 ? n : 1;
	sc.acc /= n > 0 ? n : 1;
	return sc;
}

static void prepare(Opts *o, Table **tp, int *target)
{
	Table *t = data_load(o->source, o->max_rows);
	data_analyze(t);
	*target = data_pick_target(t, o->target);
	data_drop_leaks(t, *target);
	*tp = t;
}

static int cmd_train(Opts *o)
{
	Table *t;
	int target;
	prepare(o, &t, &target);
	data_describe(t, target, stderr);

	/* rows with a usable target, split train/validation */
	int *rows = xmalloc((size_t)t->nrows * sizeof *rows), n = 0;
	const Col *tc = &t->col[target];
	for (int r = 0; r < t->nrows; r++)
		if (tc->cell[r].t != CELL_NULL) rows[n++] = r;
	if (n < 2) die(NULL, 0, "fewer than 2 rows have a value for '%s'", tc->name);
	rs = (uint32_t)(o->seed ? o->seed : 1) * 2654435761u + 1;
	shuffle(rows, n);
	int nval = (int)(n * o->val);
	if (n >= 10 && nval < 1) nval = 1;
	if (n < 10) nval = 0;
	int ntr = n - nval;
	Spec *s = spec_fit(t, target, rows, ntr, o->text_dim);

	int D = s->dim, C = s->classify ? s->nclass : 1;
	float *X = xmalloc((size_t)t->nrows * (size_t)D * sizeof *X), *Y = xmalloc((size_t)t->nrows * (size_t)C * sizeof *Y);
	int *lab = xmalloc((size_t)t->nrows * sizeof *lab);
	int k = 0, split = ntr; /* drop rows whose target class was unseen in training */
	for (int i = 0; i < n; i++) {
		int r = rows[i];
		if (spec_apply(s, t, r, X + (size_t)r * (size_t)D, Y + (size_t)r * (size_t)C, &lab[r])) rows[k++] = r;
		else if (i < split) ntr--;
		else nval--;
	}
	int *tr = rows, *va = rows + ntr;
	if (!nval) va = tr, nval = ntr; /* tiny data: report training fit */

	int H = o->hidden ? o->hidden : D <= 8 ? 16 : D <= 64 || D > 512 ? 32 : 64; /* wide sparse inputs: narrow layer */
	const char *opt = o->optimizer ? o->optimizer : "adamw";
	double lr = o->lr > 0 ? o->lr : 0.003;
	int epochs = o->epochs ? o->epochs : (int)fmin(300, fmax(20, ceil(100000.0 / ntr)));
	char name[64];
	model_name(o->source, name, sizeof name);
	char dflt[128];
	snprintf(dflt, sizeof dflt, "%s_model", name);
	const char *dir = o->out ? o->out : dflt;
	mkdir(dir, 0755);

	char *src = gen_model(name, s, H, opt, lr, o->source, 0);
	char *mpath = join(dir, "model.tg");
	write_text(mpath, src);
	Module *m = lower(surface_parse(src, mpath), mpath);
	plan(m);
	/* evaluation: the same model with updates (and so the backward pass) removed,
	 * reading the training model's weights in place */
	Module *em = lower(surface_parse(src, mpath), mpath);
	mod_strip_updates(em);
	for (int v = 0; v < em->nval; v++)
		if (em->val[v].kind == V_STATE)
			for (int w = 0; w < m->nval; w++)
				if (m->val[w].kind == V_STATE && !strcmp(m->val[w].name, em->val[v].name)) em->val[v].data = m->val[w].data;
	plan(em);

	fprintf(stderr, "\nmodel    %d -> %d (gelu) -> %d, %s(lr=%g), %d training / %d validation rows, up to %d epochs\n",
		D, H, C, opt, lr, ntr, va == tr ? 0 : nval, epochs);
	fprintf(stderr, "\n%6s %12s %12s %10s\n", "epoch", "train loss", "val loss", s->classify ? "val acc" : "val rmse");

	int afl = m->arena > em->arena ? m->arena : em->arena;
	float *arena = xmalloc((size_t)(afl ? afl : 1) * sizeof(float));
	float *out = xmalloc((size_t)C * sizeof(float));
	int *steps = xmalloc((size_t)(m->nthink ? m->nthink : 1) * sizeof(int));
	/* best-weights snapshot over the user states */
	int nst = 0;
	for (int v = 0; v < m->nval; v++) nst += m->val[v].kind == V_STATE;
	float **snap = xmalloc((size_t)(nst ? nst : 1) * sizeof *snap);
	for (int v = 0, i = 0; v < m->nval; v++)
		if (m->val[v].kind == V_STATE) snap[i++] = xmalloc((size_t)shape_numel(&m->val[v].sh) * sizeof(float));
	double best = INFINITY;
	int best_ep = 0, patience = (int)fmax(10, epochs / 5);
	Score bv = { 0, 0 };
	double t0 = tr_now_ms();
	for (int ep = 1; ep <= epochs; ep++) {
		shuffle(tr, ntr);
		Score st = run_rows(m, s, X, Y, lab, tr, ntr, arena, out, steps);
		Score sv = run_rows(em, s, X, Y, lab, va, nval, arena, out, steps);
		int improved = sv.loss < best - 1e-9;
		if (improved) {
			best = sv.loss;
			best_ep = ep;
			bv = sv;
			for (int v = 0, i = 0; v < m->nval; v++)
				if (m->val[v].kind == V_STATE) memcpy(snap[i++], m->val[v].data, (size_t)shape_numel(&m->val[v].sh) * sizeof(float));
		}
		double metric = s->classify ? sv.acc * 100 : sqrt(sv.loss) * s->tstd;
		if (ep <= 3 || improved || ep % 10 == 0 || ep == epochs)
			fprintf(stderr, "%6d %12.5f %12.5f %9.2f%s%s\n", ep, st.loss, sv.loss, metric, s->classify ? "%" : "", improved ? "  *" : "");
		if (ep - best_ep >= patience) {
			fprintf(stderr, "early stop: no validation improvement for %d epochs\n", patience);
			break;
		}
	}
	for (int v = 0, i = 0; v < m->nval; v++)
		if (m->val[v].kind == V_STATE) memcpy(m->val[v].data, snap[i++], (size_t)shape_numel(&m->val[v].sh) * sizeof(float));

	/* artifacts */
	for (int v = 0; v < m->nval; v++) {
		const Value *x = &m->val[v];
		if (x->kind != V_STATE || !strncmp(x->name, "__", 2)) continue;
		char fn[128];
		snprintf(fn, sizeof fn, "weights.%s.bin", x->name);
		char *p = join(dir, fn);
		FILE *f = fopen(p, "wb");
		if (!f) die(NULL, 0, "cannot write '%s'", p);
		io_write_row(f, 1, x->data, shape_numel(&x->sh), NULL, 0);
		if (fclose(f)) die(NULL, 0, "write failed '%s'", p);
	}
	char *spath = join(dir, "features.tgf");
	spec_save(s, spath);
	char *isrc = gen_model(name, s, H, opt, lr, o->source, 1);
	char *ipath = join(dir, "infer.tg");
	write_text(ipath, isrc);
	Module *im = load_module(ipath);
	plan(im);
	char *cpath = join(dir, "infer.c");
	FILE *cf = fopen(cpath, "w");
	if (!cf) die(NULL, 0, "cannot write '%s'", cpath);
	cgen(im, cf);
	if (fclose(cf)) die(NULL, 0, "write failed '%s'", cpath);

	char rep[2048];
	double metric = s->classify ? bv.acc * 100 : sqrt(bv.loss) * s->tstd;
	snprintf(rep, sizeof rep,
		 "source      %s (%s, %d rows)\ntask        %s of '%s'%s\nfeatures    %d\nmodel       %d -> %d -> %d, %s(lr=%g)\n"
		 "best epoch  %d (validation loss %.5f, %s %.2f%s)\ntime        %.1f s\n",
		 o->source, t->format, t->nrows, s->classify ? "classification" : "regression", s->target, "", D, D, H, C, opt, lr,
		 best_ep, bv.loss, s->classify ? "accuracy" : "rmse", metric, s->classify ? "%" : "", (tr_now_ms() - t0) / 1e3);
	char *rpath = join(dir, "report.txt");
	write_text(rpath, rep);
	fprintf(stderr, "\n%s\nwrote %s/: model.tg (training), infer.tg + weights.*.bin (inference), infer.c (C unit),\n"
			"      features.tgf (featurization), report.txt\nnext:  tgc predict %s NEW_DATA\n",
		rep, dir, dir);
	return 0;
}

static int cmd_predict(int argc, char **argv)
{
	if (argc < 4) usage_data();
	const char *dir = argv[2], *src = argv[3], *outp = NULL;
	for (int i = 4; i < argc; i++) {
		if (!strcmp(argv[i], "-o") && i + 1 < argc) outp = argv[++i];
		else die(NULL, 0, "unexpected argument '%s'", argv[i]);
	}
	Spec *s = spec_load(join(dir, "features.tgf"));
	Module *m = load_module(join(dir, "infer.tg"));
	plan(m);
	Table *t = data_load(src, 1 << 30);
	int D = s->dim, C = s->classify ? s->nclass : 1;
	float *x = xmalloc((size_t)D * sizeof *x), *out = xmalloc((size_t)C * sizeof *out);
	int *steps = xmalloc((size_t)(m->nthink ? m->nthink : 1) * sizeof *steps);
	FILE *f = outp ? fopen(outp, "w") : stdout;
	if (!f) die(NULL, 0, "cannot write '%s'", outp);
	fprintf(f, s->classify ? "prediction,confidence\n" : "prediction\n");
	int known = 0, correct = 0;
	double se = 0;
	for (int r = 0; r < t->nrows; r++) {
		int lab = -1;
		float y = 0;
		int has = spec_apply(s, t, r, x, s->classify ? NULL : &y, s->classify ? &lab : NULL);
		const float *in[1] = { x };
		vm_run(m, in, out, steps);
		if (s->classify) {
			int b = 0;
			for (int c = 1; c < C; c++)
				if (out[c] > out[b]) b = c;
			fputc('"', f);
			for (const char *p = s->classes[b]; *p; p++) {
				if (*p == '"') fputc('"', f);
				fputc(*p, f);
			}
			fprintf(f, "\",%.4f\n", (double)out[b]);
			if (has) { known++; correct += b == lab; }
		} else {
			double v = out[0] * s->tstd + s->tmean;
			fprintf(f, "%.9g\n", v);
			if (has) { known++; se += (out[0] - y) * (out[0] - y); }
		}
	}
	if (outp && fclose(f)) die(NULL, 0, "write failed '%s'", outp);
	if (known && s->classify) fprintf(stderr, "predict: %d rows, accuracy %.2f%% on the %d rows that carry '%s'\n", t->nrows, 100.0 * correct / known, known, s->target);
	else if (known) fprintf(stderr, "predict: %d rows, rmse %.6g on the %d rows that carry '%s'\n", t->nrows, sqrt(se / known) * s->tstd, known, s->target);
	else fprintf(stderr, "predict: %d rows\n", t->nrows);
	return 0;
}

int autotrain_main(int argc, char **argv)
{
	Opts o = { 0 };
	o.val = 0.2;
	o.max_rows = 20000;
	o.text_dim = 1024;
	const char *cmd = argv[1];
	if (!strcmp(cmd, "predict")) return cmd_predict(argc, argv);
	if (!strcmp(cmd, "train")) {
		parse_opts(argc, argv, 2, &o);
		if (o.val < 0 || o.val >= 1) die(NULL, 0, "--val must be in [0, 1)");
		return cmd_train(&o);
	}
	/* data inspect | data prep */
	if (argc < 4) usage_data();
	const char *sub = argv[2];
	parse_opts(argc, argv, 3, &o);
	Table *t;
	int target;
	prepare(&o, &t, &target);
	if (!strcmp(sub, "inspect")) {
		data_describe(t, target, stdout);
		return 0;
	}
	if (!strcmp(sub, "prep")) {
		if (!o.out) die(NULL, 0, "data prep needs -o OUT.csv");
		int *rows = xmalloc((size_t)t->nrows * sizeof *rows);
		for (int r = 0; r < t->nrows; r++) rows[r] = r;
		Spec *s = spec_fit(t, target, rows, t->nrows, o.text_dim);
		int D = s->dim, C = s->classify ? s->nclass : 1, kept = 0;
		float *x = xmalloc((size_t)D * sizeof *x), *y = xmalloc((size_t)C * sizeof *y);
		FILE *f = fopen(o.out, "w");
		if (!f) die(NULL, 0, "cannot write '%s'", o.out);
		fprintf(f, "# %d features then %d target value(s) per row; featurization in %s.tgf\n", D, C, o.out);
		for (int r = 0; r < t->nrows; r++) {
			if (!spec_apply(s, t, r, x, y, NULL)) continue;
			for (int i = 0; i < D; i++) fprintf(f, "%.6g,", (double)x[i]);
			for (int i = 0; i < C; i++) fprintf(f, "%.6g%s", (double)y[i], i + 1 < C ? "," : "\n");
			kept++;
		}
		if (fclose(f)) die(NULL, 0, "write failed '%s'", o.out);
		char *sp = xmalloc(strlen(o.out) + 8);
		sprintf(sp, "%s.tgf", o.out);
		spec_save(s, sp);
		fprintf(stderr, "prep: %d rows x (%d features + %d target) -> %s\n", kept, D, C, o.out);
		return 0;
	}
	usage_data();
	return 2;
}
